// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Categoria struct {
	ID        string    `json:"id"`
	Nome      string    `json:"nome"`
	Descricao *string   `json:"descricao,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type Insumo struct {
	ID          string    `json:"id"`
	Nome        string    `json:"nome"`
	CategoriaID int       `json:"categoriaId"`
	MaxSales    int       `json:"maxSales"`
	MaxLeadTime int       `json:"maxLeadTime"`
	AvgSales    int       `json:"avgSales"`
	AvgLeadTime int       `json:"avgLeadTime"`
	SafetyStock int       `json:"safetyStock"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Movimentacao struct {
	ID               string                 `json:"id"`
	InsumoID         int                    `json:"insumoId"`
	Tipo             string                 `json:"tipo"`
	Quantidade       int                    `json:"quantidade"`
	SaldoResultante  int                    `json:"saldoResultante"`
	Metadados        map[string]interface{} `json:"metadados,omitempty"`
	DataMovimentacao time.Time              `json:"dataMovimentacao"`
}

type Mutation struct {
}

type Query struct {
}
