package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"context"
	"fmt"
	"strconv"
	"logistruct-backend/graph/model"
)

// CreateInsumo is the resolver for the createInsumo field.
func (r *mutationResolver) CreateInsumo(ctx context.Context, nome string, categoriaID int, maxSales int, maxLeadTime int, avgSales int, avgLeadTime int) (*model.Insumo, error) {
	query := `INSERT INTO insumos (nome, categoria_id, max_sales, max_lead_time, avg_sales, avg_lead_time) 
			  VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, created_at, updated_at`
	var i model.Insumo
	var idInt int
	err := r.DB.QueryRow(ctx, query, nome, categoriaID, maxSales, maxLeadTime, avgSales, avgLeadTime).Scan(&idInt, &i.CreatedAt, &i.UpdatedAt)
	if err != nil {
		return nil, fmt.Errorf("failed to create insumo: %w", err)
	}
	
	i.ID = strconv.Itoa(idInt)
	i.Nome = nome
	i.CategoriaID = categoriaID
	i.MaxSales = maxSales
	i.MaxLeadTime = maxLeadTime
	i.AvgSales = avgSales
	i.AvgLeadTime = avgLeadTime
	// Cálculo do CGO Rust
	i.SafetyStock = int(r.RustEngine.SafetyStock(int32(maxSales), int32(maxLeadTime), int32(avgSales), int32(avgLeadTime)))
	return &i, nil
}

// RegisterMovement is the resolver for the registerMovement field.
func (r *mutationResolver) RegisterMovement(ctx context.Context, insumoID int, tipo string, quantidade int, metadados map[string]interface{}) (*model.Movimentacao, error) {
	// Log de auditoria, append only.
	// Primeiro pegar o saldo resultante anterior
	var lastSaldo int
	saldoQuery := `SELECT saldo_resultante FROM movimentacoes WHERE insumo_id = $1 ORDER BY id DESC LIMIT 1`
	err := r.DB.QueryRow(ctx, saldoQuery, insumoID).Scan(&lastSaldo)
	if err != nil && err.Error() != "no rows in result set" {
		return nil, fmt.Errorf("failed to fetch previous saldo: %w", err)
	}

	novoSaldo := lastSaldo + quantidade

	query := `INSERT INTO movimentacoes (insumo_id, tipo, quantidade, saldo_resultante, metadados) 
			  VALUES ($1, $2, $3, $4, $5) RETURNING id, data_movimentacao`
	
	var mov model.Movimentacao
	var idInt int
	err = r.DB.QueryRow(ctx, query, insumoID, tipo, quantidade, novoSaldo, metadados).Scan(&idInt, &mov.DataMovimentacao)
	if err != nil {
		return nil, fmt.Errorf("audit log insert failed: %w", err)
	}

	mov.ID = strconv.Itoa(idInt)
	mov.InsumoID = insumoID
	mov.Tipo = tipo
	mov.Quantidade = quantidade
	mov.SaldoResultante = novoSaldo
	mov.Metadados = metadados
	return &mov, nil
}

// Saldo is the resolver for the saldo field.
func (r *queryResolver) Saldo(ctx context.Context, insumoID int) (int, error) {
	var saldo int
	err := r.DB.QueryRow(ctx, `SELECT saldo_resultante FROM movimentacoes WHERE insumo_id = $1 ORDER BY id DESC LIMIT 1`, insumoID).Scan(&saldo)
	if err != nil {
		return 0, nil // ou tratar no rows
	}
	return saldo, nil
}

// Historico is the resolver for the historico field.
func (r *queryResolver) Historico(ctx context.Context, insumoID int) ([]*model.Movimentacao, error) {
	rows, err := r.DB.Query(ctx, "SELECT id, tipo, quantidade, saldo_resultante, metadados, data_movimentacao FROM movimentacoes WHERE insumo_id = $1 ORDER BY id DESC", insumoID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var result []*model.Movimentacao
	for rows.Next() {
		var mov model.Movimentacao
		var idInt int
		if err := rows.Scan(&idInt, &mov.Tipo, &mov.Quantidade, &mov.SaldoResultante, &mov.Metadados, &mov.DataMovimentacao); err != nil {
			continue
		}
		mov.ID = strconv.Itoa(idInt)
		mov.InsumoID = insumoID
		result = append(result, &mov)
	}
	return result, nil
}

// Insumos is the resolver for the insumos field.
func (r *queryResolver) Insumos(ctx context.Context) ([]*model.Insumo, error) {
	rows, err := r.DB.Query(ctx, "SELECT id, nome, categoria_id, max_sales, max_lead_time, avg_sales, avg_lead_time, created_at, updated_at FROM insumos ORDER BY id DESC")
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var insumos []*model.Insumo
	for rows.Next() {
		var i model.Insumo
		var idInt int
		if err := rows.Scan(&idInt, &i.Nome, &i.CategoriaID, &i.MaxSales, &i.MaxLeadTime, &i.AvgSales, &i.AvgLeadTime, &i.CreatedAt, &i.UpdatedAt); err != nil {
			continue
		}
		i.ID = strconv.Itoa(idInt)
		i.SafetyStock = int(r.RustEngine.SafetyStock(int32(i.MaxSales), int32(i.MaxLeadTime), int32(i.AvgSales), int32(i.AvgLeadTime)))
		insumos = append(insumos, &i)
	}
	return insumos, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
